language: node_js
node_js:
    - '10.15.1'
dist: trusty
sudo: required

addons:
    chrome: stable

branches:
    only:
        - master

before_script:
    - npm i -g @angular/cli

script:
    - npm run build
    - npm run lint
    - npm run test -- --no-watch
    - npm run e2e
